import os
import time
import feedparser
from datetime import datetime

# ==========================================
# Weeb - The Autonomous Anime Agent 🤖
# ==========================================

# 1. RSS Feeds to Monitor
RSS_FEEDS = {
    "news": "https://www.animenewsnetwork.com/news/rss.xml",
    # We can add more feeds for 'reviews' and 'recommendations' later
}

# Your Gemini / Groq API Key (Set this in Github Secrets later)
API_KEY = os.environ.get("WEEB_API_KEY", "")

def rewrite_article_with_llm(title, summary, link, category):
    """
    This function acts as Weeb's brain. 
    It will take the original article and rewrite it using an LLM API.
    """
    print(f"[*] Weeb's brain is processing: {title}")
    
    # TODO: In the next step, we will connect this directly to Groq API or Gemini API.
    # For now, Weeb will just create a perfectly formatted Markdown file!
    
    timestamp = int(time.time())
    date_str = datetime.now().strftime('%b %d, %Y')
    
    markdown_template = f"""---
id: "{timestamp}"
title: "{title} (Rewritten by Weeb)"
date: "{date_str}"
snippet: "This article was autonomously caught and generated by Weeb! Read more to find out."
img: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-2q1q2Q9X2X2z.png"
author: "Weeb"
---

This is an automated post generated by **Weeb**, your friendly neighborhood Anime AI Agent! 🚀

### Original News
**Title:** {title}
**Source:** [Read Original]({link})

Here is what Weeb extracted from the RSS feed before rewriting it with AI:

> {summary}

---
*Stay tuned! Soon I will be connected to a real LLM API so I can completely rewrite this text for SEO!*
"""
    return markdown_template

def process_feed(category, feed_url):
    print(f"[*] Weeb is reading {category} feed: {feed_url}")
    feed = feedparser.parse(feed_url)
    
    # Weeb only looks at the first 2 latest news so we don't spam the site
    for entry in feed.entries[:2]:
        title = entry.title
        link = entry.link
        summary = entry.get('summary', entry.get('description', ''))
        
        # Make a safe filename from the title
        safe_title = "".join([c for c in title if c.isalnum() or c==' ']).rstrip()
        filename = safe_title.replace(" ", "-").lower()[:50] + ".md"
        filepath = os.path.join("content", category, filename)
        
        # If Weeb already wrote this, skip it
        if os.path.exists(filepath):
            print(f"[-] Weeb already wrote about this: {title}")
            continue
            
        print(f"[+] Weeb found new {category}: {title}")
        
        # Ask LLM to rewrite
        markdown_content = rewrite_article_with_llm(title, summary, link, category)
        
        # Save the new article to the site
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
            
        print(f"[SUCCESS] Weeb successfully published: {filename}")

def main():
    print("==========================================")
    print("🤖 Weeb Agent is waking up...")
    print("==========================================")
    
    for category, url in RSS_FEEDS.items():
        try:
            process_feed(category, url)
        except Exception as e:
            print(f"[ERROR] Weeb got confused in {category}: {e}")
            
    print("==========================================")
    print("🤖 Weeb Agent is going back to sleep. Zzz...")
    print("==========================================")

if __name__ == "__main__":
    main()
