import fs from 'fs';
import path from 'path';

export function generateStaticParams() {
  const dbPath = path.join(process.cwd(), 'data', 'db.json');
  let dbData = { news: [] };
  try {
    dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
  } catch(e) {}
  
  return dbData.news.map((n) => ({ id: n.id.toString() }));
}

export default async function NewsDetail({ params }) {
  const resolvedParams = await params;
  const dbPath = path.join(process.cwd(), 'data', 'db.json');
  let dbData = { news: [] };
  try {
    dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
  } catch(e) {}

  const article = dbData.news.find(n => n.id.toString() === resolvedParams.id) || dbData.news[0];
  
  if (!article) return <div className="main-wrapper" style={{padding: '20px'}}>News not found</div>;

  return (
    <div className="main-wrapper news-detail-page">
      
      {/* Top Breadcrumb Bar */}
      <div className="news-top-bar">
        <h2 className="news-section-title">Anime & Manga News</h2>
        <div className="breadcrumbs">
          Top &gt; News &gt; {article.title}
        </div>
      </div>

      <div style={{display: "flex", flexDirection: "column", '@media(minWidth: 768px)': {flexDirection: "row"}}}>
        
        {/* Left Main Content */}
        <div className="news-main-col" style={{width: '100%', flexGrow: 1}}>
          <h1 className="news-headline">{article.title}</h1>
          
          <div className="news-meta-bar">
            <div className="news-author-info">
              by <a href="#">WeebHQ AI</a><br/>
              <span>{article.date} | <a href="#">0 comments</a></span>
            </div>
            <div className="news-socials">
              <a href="#">F</a> <a href="#">X</a> <a href="#">R</a> <a href="#">T</a>
            </div>
          </div>
          
          <div className="news-content-body" style={{minHeight: '400px'}}>
            <img src={article.img} alt="News Image" className="news-float-img" />
            
            <div style={{fontSize: '14px', lineHeight: '1.6'}} dangerouslySetInnerHTML={{ __html: article.fullText || `<p>${article.snippet}</p>` }} />
            
            <br/>
            <p style={{fontSize: '12px', color: '#666'}}>
              <strong>Powered by Google Gemini 3.8 Flash.</strong><br/>
              This article was automatically generated by WeebHQ's AI Engine based on the latest trending data from Kitsu.
            </p>
          </div>
          
          <div className="news-tags">
            <a href="#" className="tag-pill">AI Generated</a>
            <a href="#" className="tag-pill">Trending</a>
          </div>

          <div className="news-comments-section">
            <div className="comments-header">
              <h3>Recent Comments</h3>
              <a href="#">0 Comments</a>
            </div>
            <p style={{padding: '10px', fontSize: '11px', color: '#666'}}>Be the first to comment on this AI-generated news!</p>
          </div>

        </div>

      </div>
    </div>
  );
}
